version: "3.9"
services:
  redis:
    image: redis
    volumes:
    - ./assets/data/redis:/data
    ports:
    - 127.0.0.1:6379:6379
  mysql:
    image: mysql:5.7.33
    environment:
    - MYSQL_ROOT_PASSWORD=chen1399
    - MYSQL_USER=lucid
    - MYSQL_PASSWORD=qwer1234
    volumes:
    - ./assets/data/mysql:/var/lib/mysql
    ports:
    - 127.0.0.1:3306:3306
  delivery:
    build: ./delivery
    image: delivery
    environment:
    - PORT=3332
    - HOST=0.0.0.0
    - NODE_ENV=development
    - APP_KEY=XquabEMKf30EACiCPpoeIkC3dMy6-689
    - DB_CONNECTION=mysql
    - MYSQL_HOST=mysql
    - MYSQL_PORT=3306
    - MYSQL_USER=lucid
    - MYSQL_PASSWORD=qwer1234
    - MYSQL_DB_NAME=delivery
    - REDIS_CONNECTION=local
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    depends_on:
    - mysql
    - redis
